### ISSUE TITLE
Increase use of labels throughout all VFL repositories 

### ISSUE THREAD

**Issue by fadedmax** [Voxel-Fox-Ltd/Meta#12]
Personally i think labels are a amazing thing, but it'd be nice if we actually started using them. Some repos like apple.py have quite a few issues, and having a priority label for how much kae cares about them would be nice, so that people don't implement a feature you don't care about.

**Comment by 4Kaylum** [comment]
Which labels do you want to have implemented? The default Github ones may not be the most apt for my stuff.
